# Generated by Django 2.1.7 on 2019-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_walletID', models.IntegerField()),
                ('to_walletID', models.IntegerField()),
                ('to_emailaddress', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('emailaddress', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_id', models.CharField(max_length=50)),
                ('signup_token', models.CharField(max_length=50)),
                ('signup_timestamp', models.DateTimeField(auto_now_add=True)),
                ('suspend', models.CharField(default='False', max_length=30)),
                ('picture', models.ImageField(default='profile_image/default.jpg', max_length=255, upload_to='profile_image')),
                ('signin_token', models.CharField(max_length=50)),
                ('signin_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
