# Generated by Django 2.1.7 on 2019-04-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troyapi', '0002_admin_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('sender_user_id', models.IntegerField()),
                ('reeceiver_user_id', models.IntegerField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
