# Generated by Django 2.1.7 on 2019-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troyapi', '0004_chatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='suspend',
            field=models.CharField(default='False', max_length=30),
        ),
    ]
